# Generated by Django 3.2.19 on 2023-05-03 14:40

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='proprietario',
            field=models.ForeignKey(default=1, on_delete=core.models.Pessoa, to='core.pessoa'),
            preserve_default=False,
        ),
    ]
